Import new-submission posts and replace content with our new text
adelikat/tasvideos pull request #527
Opened 2021-10-05 17:44 UTC by Masterjun3

**UNTESTED**, because I have no access to posts of the legacy database.

This aims to import the old new-submission posts from TASVideoAgent and replaces the content with our current system.
The corresponding Submission ID is extracted from the post subject string.
It is effectively the same as the publication post replacement right above the new code.

This fixes the current issue of the first post not being by TVA, meaning the title is editable by the first person to post.
If this works properly, it would remove the need for the recent addition of the `ForumPostFixer.cs`.

2021-10-05 19:56 UTC, adelikat requested changes
Requesting changes for the nitpick mentioned below

2021-10-05 21:04 UTC, Masterjun3 commented on TASVideos.Legacy/Imports/ForumPostsImporter.cs
> +						fixedText = SiteGlobalConstants.NewSubmissionPost + $"[submission]{submissionId}[/submission]";
resolved! and the bot reports comments maybe?

2021-10-05 22:36 UTC, Masterjun3 commented
Okay, this breaks as it is now, do not merge yet! :D

2021-10-06 23:26 UTC, adelikat approved these changes

2021-10-06 23:26 UTC, merged